name: Build PDF on Markdown Commit

on:
  push:
    paths: 
        []
#       - resume.md

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run Python script
        run: python resume.py
